// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1myjKoATiXRJBkDk0Fu4buKaTS41xy4',
    appId: '1:669920565478:web:2df04c5bc1883dc5398327',
    messagingSenderId: '669920565478',
    projectId: 'horizon-fd023',
    authDomain: 'horizon-fd023.firebaseapp.com',
    storageBucket: 'horizon-fd023.firebasestorage.app',
    measurementId: 'G-84KHXVEM57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ105_mH4-hOrAvLQ1gxsC2rdpY4s-Q2A',
    appId: '1:669920565478:android:63d63c26f44303f2398327',
    messagingSenderId: '669920565478',
    projectId: 'horizon-fd023',
    storageBucket: 'horizon-fd023.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP1myjKoATiXRJBkDk0Fu4buKaTS41xy4',
    appId: '1:669920565478:web:620fb375c3ba950c398327',
    messagingSenderId: '669920565478',
    projectId: 'horizon-fd023',
    authDomain: 'horizon-fd023.firebaseapp.com',
    storageBucket: 'horizon-fd023.firebasestorage.app',
    measurementId: 'G-7VXBY7WY5N',
  );
}
